### ISSUE TITLE
Ideas about why the quality isn't as good?

### ISSUE THREAD

**Issue by roedoejet** [rishikksh20/iSTFT-Avocodo-pytorch#3]
Thanks for this repo - and for all your other excellent work! It is very appreciated. This seems like a very reasonable idea to combine the generator from iSTFT-net and the discriminators from Avocado. But then in your notes you say "Quality is not as good as Avocodo and ISTFTNet." - how much worse was it, and do you have any ideas about why the quality is not as good?

**Comment by SynthAether** [comment]
Indeed thanks Rishikesh for your excellent work.

I tried both Avocodo's discriminators on HiFi-GAN and on iSTFTNet, though on slightly different implementations to Rishikesh's excellent work. What I notice is Avocodo with iSTFTNet sounds slightly less good than plain iSTFTNet, but only by a slight margin that can only be noticed with careful listening. I suspect the reason is because the generator of iSTFTNet uses less intermediate outputs (i.e. number of tansposed layers) than a HiFi-GAN, meaning there are less outputs produced for Avocodo's discriminator to do its work.

**Comment by roedoejet** [comment]
right - that makes sense - thanks for sharing!

**Comment by rishikksh20** [comment]
yes, quality degradation only noticeable when you hear carefully on headphone.
